language: python
branches:
  only:
    - main
before_install:
  - export TZ=America/Sao_Paulo   
#install:
# -  
before_script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "TravisCI"
  - git config --global push.default "matching"
script:
  - bash build.sh
